name: pciu_hubspot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.1
  fluttertoast: ^8.2.8
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/services/
    - assets/images/links/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"