import 'package:pciu_hubspot/core/models/batch_coordinator_model.dart';

List<BatchCoordinatorModel> batchCoordinators = [
  BatchCoordinatorModel(
    name: 'Mrs. Taslima Binte Hossain',
    batches: ['CSE-25-D-A', 'CSE-26-D-A', 'CSE-31-D-B'],
    shortForm: 'T.H.',
    room: '101',
    department: 'CSE',
    contact: '017XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Rahman Ali',
    batches: ['CSE-24-D-B', 'CSE-26-D-A', 'CSE-33-D-B', 'CSE-27-D-B'],
    shortForm: 'R.A.',
    room: '102',
    department: 'CSE',
    contact: '018XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Mohammad Saiful Islam',
    batches: ['CSE-23-D-B', 'CSE-29-D-B', 'CSE-33-D-C'],
    shortForm: 'S.I.',
    room: '202',
    department: 'EEE',
    contact: '019XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mrs. Nuzhat Anjum',
    batches: ['CSE-28-D-A', 'CSE-32-D-B'],
    shortForm: 'N.A.',
    room: '104',
    department: 'CSE',
    contact: '016XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Abdullah Al Mamun',
    batches: ['EEE-22-D-A', 'EEE-25-D-C', 'EEE-30-D-A'],
    shortForm: 'A.M.',
    room: '205',
    department: 'EEE',
    contact: '015XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Dr. Rubina Sultana',
    batches: ['BBA-20-D-B', 'BBA-22-D-C', 'BBA-30-D-A'],
    shortForm: 'R.S.',
    room: '303',
    department: 'BBA',
    contact: '014XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Kamal Hossain',
    batches: ['CSE-24-D-A', 'CSE-30-D-A', 'CSE-35-D-C'],
    shortForm: 'K.H.',
    room: '106',
    department: 'CSE',
    contact: '019XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mrs. Fatema Akter',
    batches: ['EEE-26-D-A', 'EEE-29-D-B', 'EEE-32-D-A'],
    shortForm: 'F.A.',
    room: '208',
    department: 'EEE',
    contact: '013XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Mahmudul Hasan',
    batches: ['BBA-21-D-B', 'BBA-26-D-A', 'BBA-33-D-B'],
    shortForm: 'M.H.',
    room: '305',
    department: 'BBA',
    contact: '017XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Dr. Sabrina Islam',
    batches: ['CSE-25-D-B', 'CSE-29-D-C', 'CSE-33-D-A'],
    shortForm: 'S.I.',
    room: '107',
    department: 'CSE',
    contact: '018XXXXXXXX',
  ),
  BatchCoordinatorModel(
    name: 'Mr. Rashedul Alam',
    batches: ['EEE-24-D-B', 'EEE-28-D-C', 'EEE-34-D-B'],
    shortForm: 'R.A.',
    room: '210',
    department: 'EEE',
    contact: '016XXXXXXXX',
  ),
];
