import 'package:pciu_hubspot/core/models/cr_model.dart';

final List<CR> crList = [
  CR(
    name: 'Nadim Chowdhury',
    batch: '2024',
    department: 'CSE',
    shift: 'Morning',
    section: 'A',
    contact: '01711-123456',
    email: 'nadim.chowdhury@example.com',
    facebookId: 'nadim.chowdhury.fb',
  ),
  CR(
    name: 'Ayesha Rahman',
    batch: '2024',
    department: 'EEE',
    shift: 'Evening',
    section: 'B',
    contact: '01822-654321',
    email: 'ayesha.rahman@example.com',
    facebookId: 'ayesha.rahman.fb',
  ),
  CR(
    name: 'Tanvir Ahmed',
    batch: '2025',
    department: 'BBA',
    shift: 'Morning',
    section: 'C',
    contact: '01633-555123',
    email: 'tanvir.ahmed@example.com',
    facebookId: 'tanvir.ahmed.fb',
  ),
  CR(
    name: 'Shamima Akter',
    batch: '2022',
    department: 'Mechanical',
    shift: 'Evening',
    section: 'D',
    contact: '01544-789123',
    email: 'shamima.akter@example.com',
    facebookId: 'shamima.akter.fb',
  ),
  CR(
    name: 'Rafiq Islam',
    batch: '2023',
    department: 'CSE',
    shift: 'Morning',
    section: 'A',
    contact: '01712-456789',
    email: 'rafiq.islam@example.com',
    facebookId: 'rafiq.islam.fb',
  ),
];
