import 'package:pciu_hubspot/core/models/cr_model.dart';

final List<CR> crList = [
  CR(
    name: 'Nadim Chowdhury',
    batch: '2024',
    department: 'CSE',
    shift: 'Morning',
    section: 'A',
    contact: '01711-123456',
    email: 'nadim.chowdhury@example.com',
    facebookId: 'nadim.chowdhury.fb',
  ),
  CR(
    name: 'Ayesha Rahman',
    batch: '2024',
    department: 'EEE',
    shift: 'Evening',
    section: 'B',
    contact: '01822-654321',
    email: 'ayesha.rahman@example.com',
    facebookId: 'ayesha.rahman.fb',
  ),
  CR(
    name: 'Tanvir Ahmed',
    batch: '2025',
    department: 'BBA',
    shift: 'Morning',
    section: 'C',
    contact: '01633-555123',
    email: 'tanvir.ahmed@example.com',
    facebookId: 'tanvir.ahmed.fb',
  ),
  CR(
    name: 'Shamima Akter',
    batch: '2022',
    department: 'Mechanical',
    shift: 'Evening',
    section: 'D',
    contact: '01544-789123',
    email: 'shamima.akter@example.com',
    facebookId: 'shamima.akter.fb',
  ),
  CR(
    name: 'Rafiq Islam',
    batch: '2023',
    department: 'CSE',
    shift: 'Morning',
    section: 'A',
    contact: '01712-456789',
    email: 'rafiq.islam@example.com',
    facebookId: 'rafiq.islam.fb',
  ),
  CR(
    name: 'Mariam Siddique',
    batch: '2024',
    department: 'Architecture',
    shift: 'Evening',
    section: 'B',
    contact: '01333-789456',
    email: 'mariam.siddique@example.com',
    facebookId: 'mariam.siddique.fb',
  ),
  CR(
    name: 'Ibrahim Khalil',
    batch: '2025',
    department: 'EEE',
    shift: 'Morning',
    section: 'C',
    contact: '01999-234567',
    email: 'ibrahim.khalil@example.com',
    facebookId: 'ibrahim.khalil.fb',
  ),
  CR(
    name: 'Sadia Alam',
    batch: '2023',
    department: 'BBA',
    shift: 'Morning',
    section: 'A',
    contact: '01766-654321',
    email: 'sadia.alam@example.com',
    facebookId: 'sadia.alam.fb',
  ),
  CR(
    name: 'Tariqul Islam',
    batch: '2022',
    department: 'Civil',
    shift: 'Evening',
    section: 'D',
    contact: '01577-987654',
    email: 'tariqul.islam@example.com',
    facebookId: 'tariqul.islam.fb',
  ),
  CR(
    name: 'Fahim Hassan',
    batch: '2025',
    department: 'CSE',
    shift: 'Morning',
    section: 'B',
    contact: '01888-112233',
    email: 'fahim.hassan@example.com',
    facebookId: 'fahim.hassan.fb',
  ),
  CR(
    name: 'Rina Sultana',
    batch: '2024',
    department: 'Mechanical',
    shift: 'Evening',
    section: 'A',
    contact: '01788-556677',
    email: 'rina.sultana@example.com',
    facebookId: 'rina.sultana.fb',
  ),
  CR(
    name: 'Jamil Hossain',
    batch: '2023',
    department: 'EEE',
    shift: 'Morning',
    section: 'C',
    contact: '01677-334455',
    email: 'jamil.hossain@example.com',
    facebookId: 'jamil.hossain.fb',
  ),
];
