import 'package:pciu_hubspot/core/models/faculty_model.dart';

final List<Faculty> facultyList = [
  Faculty(
    name: 'Mrs. Farzina Akther',
    designation: 'Senior Lecturer',
    shortForm: 'MFA2',
    room: 'C403',
    department: 'CSE',
    contact: '01923829025',
  ),
  Faculty(
    name: 'Dr. Tanvir Ahmed',
    designation: 'Associate Professor',
    shortForm: 'TA3',
    room: 'C404',
    department: 'CSE',
    contact: '01923829030',
  ),
  Faculty(
    name: 'Mr. Habib Rahman',
    designation: 'Lecturer',
    shortForm: 'HR1',
    room: 'C405',
    department: 'EEE',
    contact: '01923829035',
  ),
  Faculty(
    name: 'Ms. Saima Rahman',
    designation: 'Assistant Professor',
    shortForm: 'SR4',
    room: 'C406',
    department: 'BBA',
    contact: '01923829040',
  ),
  Faculty(
    name: 'Dr. Faisal Alam',
    designation: 'Professor',
    shortForm: 'FA5',
    room: 'C407',
    department: 'ME',
    contact: '01923829045',
  ),
  Faculty(
    name: 'Mr. Alif Hossain',
    designation: 'Senior Lecturer',
    shortForm: 'AH6',
    room: 'C408',
    department: 'CSE',
    contact: '01923829050',
  ),
  Faculty(
    name: 'Mrs. Shirin Akter',
    designation: 'Lecturer',
    shortForm: 'SA7',
    room: 'C409',
    department: 'EEE',
    contact: '01923829055',
  ),
  Faculty(
    name: 'Ms. Nilufa Yasmin',
    designation: 'Lecturer',
    shortForm: 'NY8',
    room: 'C410',
    department: 'BBA',
    contact: '01923829060',
  ),
  Faculty(
    name: 'Mr. Fahim Khan',
    designation: 'Assistant Professor',
    shortForm: 'FK9',
    room: 'C411',
    department: 'ME',
    contact: '01923829065',
  ),
  Faculty(
    name: 'Dr. Zara Islam',
    designation: 'Professor',
    shortForm: 'ZI10',
    room: 'C412',
    department: 'CSE',
    contact: '01923829070',
  ),
];
